export const GET_BOOKS_LIST_PENDING = 'GET_BOOKS_LIST_PENDING';
export const GET_BOOKS_LIST_SUCCESS = 'GET_BOOKS_LIST_SUCCESS';
export const GET_BOOKS_LIST_FAILURE = 'GET_BOOKS_LIST_FAILURE';

export const GET_MORE_BOOKS_PENDING = 'GET_MORE_BOOKS_PENDING';
export const GET_MORE_BOOKS_SUCCESS = 'GET_MORE_BOOKS_SUCCESS';
export const GET_MORE_BOOKS_FAILURE = 'GET_MORE_BOOKS_FAILURE';
